#!/usr/bin/env node

import fs from "fs/promises";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";

const defaultSource =
  "https://raw.githubusercontent.com/anjo76/angelscript/master/sdk/angelscript/source/as_tokendef.h";

function parseArgs(argv) {
  const thisFilePath = fileURLToPath(import.meta.url);
  const scriptsDir = path.dirname(thisFilePath);
  const repoRoot = path.resolve(scriptsDir, "..", "..");
  const defaults = {
    source: process.env.OPAS_AS_TOKENDEF_SOURCE || defaultSource,
    outputJson: path.resolve(
      process.env.OPAS_AS_TOKENDEF_OUTPUT_JSON ||
        path.join(repoRoot, "test-files", "conformance", "angelscript-token-defs.json")
    ),
    outputTs: path.resolve(
      process.env.OPAS_AS_TOKENDEF_OUTPUT_TS ||
        path.join(repoRoot, "src", "server", "angelScriptTokenTables.generated.ts")
    )
  };

  const opts = { ...defaults };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    switch (arg) {
      case "--source":
        i += 1;
        opts.source = requireArgValue(argv, i, "--source");
        break;
      case "--output-json":
        i += 1;
        opts.outputJson = path.resolve(requireArgValue(argv, i, "--output-json"));
        break;
      case "--output-ts":
        i += 1;
        opts.outputTs = path.resolve(requireArgValue(argv, i, "--output-ts"));
        break;
      case "--help":
      case "-h":
        printHelpAndExit(defaults);
        break;
      default:
        throw new Error(`Unknown argument: ${arg}. Use --help for usage.`);
    }
  }

  return opts;
}

function requireArgValue(argv, index, flagName) {
  if (index >= argv.length) {
    throw new Error(`${flagName} requires a value.`);
  }
  const value = argv[index];
  if (!value || value.startsWith("-")) {
    throw new Error(`${flagName} requires a value.`);
  }
  return value;
}

function printHelpAndExit(defaults) {
  const lines = [
    "Usage: npm run test:conformance:sync-tokens -- [options]",
    "",
    "Options:",
    "  --source <url>         Source URL for as_tokendef.h.",
    "  --output-json <path>   Output JSON path.",
    "  --output-ts <path>     Output generated TypeScript path.",
    "  -h, --help             Show this help.",
    "",
    "Defaults:",
    `  source: ${defaults.source}`,
    `  output-json: ${defaults.outputJson}`,
    `  output-ts: ${defaults.outputTs}`,
    "",
    "Environment overrides:",
    "  OPAS_AS_TOKENDEF_SOURCE",
    "  OPAS_AS_TOKENDEF_OUTPUT_JSON",
    "  OPAS_AS_TOKENDEF_OUTPUT_TS"
  ];
  console.log(lines.join("\n"));
  process.exit(0);
}

async function downloadText(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function parseTokenDefs(content) {
  const tokenWords = [];
  const tokenWordPattern = /asTokenDef\("((?:[^"\\]|\\.)+)"\s*,\s*(tt[A-Za-z0-9_]+)\)/g;
  let tokenWordMatch;
  while ((tokenWordMatch = tokenWordPattern.exec(content)) !== null) {
    tokenWords.push({
      text: unescapeCStyleString(tokenWordMatch[1]),
      tokenType: tokenWordMatch[2]
    });
  }

  const contextualKeywords = [];
  const contextualPattern = /const\s+char\s*\*\s*const\s+[A-Z0-9_]+_TOKEN\s*=\s*"((?:[^"\\]|\\.)+)"/g;
  let contextualMatch;
  while ((contextualMatch = contextualPattern.exec(content)) !== null) {
    contextualKeywords.push(unescapeCStyleString(contextualMatch[1]));
  }

  const reservedKeywords = tokenWords
    .filter((entry) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(entry.text))
    .map((entry) => entry.text);

  return {
    tokenWords,
    reservedKeywords: dedupePreserveOrder(reservedKeywords),
    contextualKeywords: dedupePreserveOrder(contextualKeywords)
  };
}

function dedupePreserveOrder(values) {
  const out = [];
  const seen = new Set();
  for (const value of values) {
    if (seen.has(value)) {
      continue;
    }
    seen.add(value);
    out.push(value);
  }
  return out;
}

function unescapeCStyleString(value) {
  return value
    .replace(/\\\\/g, "\\")
    .replace(/\\"/g, "\"")
    .replace(/\\n/g, "\n")
    .replace(/\\t/g, "\t");
}

function renderGeneratedTypeScript({ source, reservedKeywords, contextualKeywords }) {
  const lines = [
    "// This file is auto-generated by scripts/conformance/syncAngelScriptTokenDefs.mjs.",
    "// Do not edit manually.",
    `// Source: ${source}`,
    `// Generated at: ${new Date().toISOString()}`,
    "",
    "export const angelScriptReservedKeywords = [",
    ...reservedKeywords.map((keyword) => `  ${JSON.stringify(keyword)},`),
    "] as const;",
    "",
    "export const angelScriptContextualKeywords = [",
    ...contextualKeywords.map((keyword) => `  ${JSON.stringify(keyword)},`),
    "] as const;",
    "",
    "export const angelScriptKeywordLikeTokens = [",
    "  ...angelScriptReservedKeywords,",
    "  ...angelScriptContextualKeywords,",
    "] as const;"
  ];
  return `${lines.join("\n")}\n`;
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const content = await downloadText(options.source);
  const parsed = parseTokenDefs(content);

  const jsonOutput = {
    ts_utc: new Date().toISOString(),
    source: options.source,
    reserved_keywords: parsed.reservedKeywords,
    contextual_keywords: parsed.contextualKeywords,
    token_words: parsed.tokenWords
  };

  await fs.mkdir(path.dirname(options.outputJson), { recursive: true });
  await fs.writeFile(options.outputJson, `${JSON.stringify(jsonOutput, null, 2)}\n`, "utf8");

  const tsOutput = renderGeneratedTypeScript({
    source: options.source,
    reservedKeywords: parsed.reservedKeywords,
    contextualKeywords: parsed.contextualKeywords
  });

  await fs.mkdir(path.dirname(options.outputTs), { recursive: true });
  await fs.writeFile(options.outputTs, tsOutput, "utf8");

  console.log(`[sync-as-tokendef] Source: ${options.source}`);
  console.log(`[sync-as-tokendef] Reserved keywords: ${parsed.reservedKeywords.length}`);
  console.log(`[sync-as-tokendef] Contextual keywords: ${parsed.contextualKeywords.length}`);
  console.log(`[sync-as-tokendef] JSON output: ${options.outputJson}`);
  console.log(`[sync-as-tokendef] TS output: ${options.outputTs}`);
}

void main().catch((error) => {
  console.error(
    `[sync-as-tokendef] FAILED: ${error instanceof Error ? error.message : String(error)}`
  );
  process.exitCode = 1;
});
